// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaContratos.Data;

#nullable disable

namespace SistemaContratos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221109164917_addedAll2")]
    partial class addedAll2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaContratos.Models.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("area");
                });

            modelBuilder.Entity("SistemaContratos.Models.Contrato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("area_id")
                        .HasColumnType("int");

                    b.Property<string>("ejercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado_contrato_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_contrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_dictamen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inactividad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("financiamiento_especial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fuente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grupo_presupuestario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motivo_baja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nro_expediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nro_resolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pagaderos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paso")
                        .HasColumnType("int");

                    b.Property<int>("persona_id")
                        .HasColumnType("int");

                    b.Property<string>("remuneracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("retribucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subunidad_presupuestaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sujeto_a")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tareas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("traslado")
                        .HasColumnType("int");

                    b.Property<string>("unidad_presupuestaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("contrato");
                });

            modelBuilder.Entity("SistemaContratos.Models.Leyenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("leyenda");
                });

            modelBuilder.Entity("SistemaContratos.Models.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("SistemaContratos.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<JsonElement>("roles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
